"""Pre-build step: write the firmware version into include/fw_version.h.

PATTERN: single source of truth for the version.
The version is not typed into the code by hand (where it would be forgotten).
It is derived from git at build time:

    v0.1.0                  built exactly from the tag v0.1.0
    v0.1.0-3-g1a2b3c4       3 commits after v0.1.0, at commit 1a2b3c4
    v0.1.0-3-g1a2b3c4-dirty ...with uncommitted changes on top
    1a2b3c4                 no tag exists yet
    0.0.0-dev               not a git checkout at all

So every binary can be traced back to the exact source it was built from,
and the device reports that string to the server on every request.

PlatformIO runs this file because platformio.ini lists it under
`extra_scripts`. `Import("env")` is how such a script gets access to the
build environment.
"""

import os
import subprocess

Import("env")  # noqa: F821  (provided by PlatformIO/SCons, not a normal import)


def describe(project_dir):
    try:
        out = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=project_dir,
            stderr=subprocess.DEVNULL,
        )
        return out.decode("utf-8").strip() or "0.0.0-dev"
    except (OSError, subprocess.CalledProcessError):
        return "0.0.0-dev"


project_dir = env["PROJECT_DIR"]  # noqa: F821
version = describe(project_dir)
header = os.path.join(project_dir, "include", "fw_version.h")
content = (
    "// Generated by scripts/git_version.py on every build. Do not edit,\n"
    "// do not commit (it is listed in .gitignore).\n"
    "#pragma once\n"
    '#define FW_VERSION "%s"\n' % version
)

# Only touch the file when the version actually changed. The build system
# recompiles everything that includes a header whose timestamp is newer than
# the last build, so rewriting identical content would force a needless
# recompile every time. (This is also why the version lives in a header
# included by one file, and not in a -D compiler flag: a changed flag
# recompiles the entire project, libraries included.)
try:
    with open(header, "r", encoding="utf-8") as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False

if not unchanged:
    with open(header, "w", encoding="utf-8") as f:
        f.write(content)

print("Firmware version: %s" % version)
