"""Pre-build step: write the firmware version into include/fw_version.h.

PATTERN: single source of truth. The version is derived from git, never
typed by hand, so every binary names the exact source it was built from:

    v0.1.0                    built from the tag v0.1.0
    v0.1.0-3-g1a2b3c4         3 commits after it, at commit 1a2b3c4
    v0.1.0-3-g1a2b3c4-dirty   ...plus uncommitted changes
    1a2b3c4                   no tag yet
    0.0.0-dev                 not a git checkout

platformio.ini lists this file under `extra_scripts`; `Import("env")` gives
it the build environment.
"""

import os
import subprocess

Import("env")  # noqa: F821  (provided by PlatformIO/SCons, not a normal import)


def describe(project_dir):
    try:
        out = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=project_dir,
            stderr=subprocess.DEVNULL,
        )
        return out.decode("utf-8").strip() or "0.0.0-dev"
    except (OSError, subprocess.CalledProcessError):
        return "0.0.0-dev"


project_dir = env["PROJECT_DIR"]  # noqa: F821
version = describe(project_dir)
header = os.path.join(project_dir, "include", "fw_version.h")
content = (
    "// Generated by scripts/git_version.py on every build. Do not edit,\n"
    "// do not commit (it is listed in .gitignore).\n"
    "#pragma once\n"
    '#define FW_VERSION "%s"\n' % version
)

# PATTERN: conditional write. Rewriting identical content would change the
# file's timestamp and force a needless recompile. (Also why the version is
# a header included by one file, not a -D flag: a changed flag recompiles
# everything, libraries included.)
try:
    with open(header, "r", encoding="utf-8") as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False

if not unchanged:
    with open(header, "w", encoding="utf-8") as f:
        f.write(content)

print("Firmware version: %s" % version)
