// Entry point of the firmware.
//
// PATTERN: composition root.
// This is the one place where the concrete pieces are created and wired
// together: the real battery, display, Wi-Fi, HTTP client, settings and
// clock are constructed here and handed to the application logic, which
// only knows their interfaces (src/app/ports.h). Everything hardware-
// specific that is not inside an adapter is in this file, and this file
// contains no decisions: it only connects things.
//
// THE LAYERS (an arrow means "may include"):
//
//     main.cpp ──> hal/ , storage/      adapters: talk to hardware
//         │            │
//         └──────> app/                 the wake cycle: decisions, no hardware
//                      │
//                   pure/               maths and rules: no dependencies at all
//
// Dependencies only point downwards. pure/ and app/ never include Arduino
// headers, which is why they can be unit tested on a laptop.
#include <Arduino.h>

#include "app/log.h"
#include "app/wake_cycle.h"
#include "config.h"
#include "fw_version.h"  // Generated by scripts/git_version.py at build time.
#include "hal/battery_adc.h"
#include "hal/board.h"
#include "hal/epaper_display.h"
#include "hal/http_screen_client.h"
#include "hal/power.h"
#include "hal/rtc_store.h"
#include "hal/wall_clock.h"
#include "hal/wifi_network.h"
#include "pure/frame.h"
#include "storage/nvs_settings.h"

namespace {

// The download buffer for one frame: 48,000 bytes.
// PATTERN: static allocation.
// `static` storage is reserved by the linker and exists for the whole run.
// Nothing is requested from the heap at run time, so the allocation cannot
// fail, cannot fragment memory, and the memory budget is known at build
// time. Embedded code prefers this for anything large with a fixed size.
uint8_t g_frame[epb::kFrameBytes];

}  // namespace

// Arduino calls setup() once after every start. Because waking from deep
// sleep IS a start, setup() runs once per wake cycle and contains the whole
// program.
void setup() {
    using namespace epb;

    // First thing: arm the safety net, before anything can hang.
    power::armAwakeLimit(config::kMaxAwakeSeconds, config::kAwakeLimitSleepSeconds);

    Serial.begin(config::kSerialBaud);
#ifdef EPB_BOOT_DELAY_MS
    delay(EPB_BOOT_DELAY_MS);  // Debug build only: let the USB serial port reconnect.
#endif
    logf("e-paperBoard firmware %s", FW_VERSION);

    // Read why we woke BEFORE touching the button pins.
    const WakeInfo wake = power::readWakeInfo();
    power::releaseButtonPins();

    // Create the adapters. Plain local objects: they live exactly as long as
    // this function, which is as long as the device is awake.
    BatteryAdc battery;
    EpaperDisplay display;
    WifiNetwork network;
    HttpScreenClient client;
    NvsSettings settings;
    WallClock clock;
    settings.applyDevSecrets();

    Ports ports = {settings, battery, display, network, client, clock};
    const CycleConfig cycleConfig = {board::kButtons, board::kButtonCount, FW_VERSION, SleepConfig{}};

    // Load state -> run one cycle -> save state -> sleep.
    const CycleResult result = runWakeCycle(wake, loadRtcState(), cycleConfig, ports, g_frame, sizeof(g_frame));
    saveRtcState(result.state);
    power::deepSleepFor(result.sleepSeconds);
}

// Arduino calls loop() over and over after setup() returns. Ours never
// returns: it ends in deep sleep. The function must still exist for the
// program to link.
void loop() {}
